### PR TITLE
Make Camera device() return an optional

### PR DESCRIPTION
**Pull request by rounak**
The example app now displays an alert in `FilterDisplayViewController` instead of crashing in `Camera` `device()` with an `EXC_BAD_ACCESS` `fatal error: unexpectedly found nil while unwrapping an Optional value`. As part of this I changed the fatalError() in the view controller to a print.

I'm still pretty new to Swift, so happy to make changes.

### CODE REVIEW

**Comment by timvermeulen** [comment]
`if videoCamera == nil { ... }`

Don't do this. Much better is `guard let videoCamera = videoCamera else { ... }` because then you can proceed to use `videoCamera` without the `!` in the remainder of the code.

**Comment by BradLarson** [comment]
To Tim's point, even without the binding of the optional value, I like using guards for early exits, because the compiler forces you to exit at that point. If you forget to add the return or something else to kick you out, it will catch that.

Still trying to figure out why you're seeing `AVCaptureDevice.devicesWithMediaType(AVMediaTypeVideo)` return `[AVCaptureDevice]` when both my Macs on Xcode 7.3 / Swift 2.2 show that returning `[AnyObject]`. The documentation here still shows `[AnyObject]!` as the return type from that:

https://developer.apple.com/library/mac/documentation/AVFoundation/Reference/AVCaptureDevice_Class/#//apple_ref/occ/clm/AVCaptureDevice/devicesWithMediaType:

You sure you're not running a Swift 3.0 toolchain or prerelease iOS snapshot in there somewhere?

**Comment by rounak** [comment]
I'm sorry if I was unclear before. I am seeing devicesWithMediaType return [AnyObject] which is why we do need the `as? AVCaptureDevice` bit.

**Comment by rounak** [comment]
Updated the PR to use guard rather than if

**Comment by timvermeulen** [comment]
Rather than writing:
```
if let videoCamera = videoCamera {
    videoCamera.stopCapture()
    ...
}
```
you can simply use:
```
videoCamera?.stopCapture()
```
It's called optional chaining.

**Comment by BradLarson** [comment]
Oh, I understand what I was seeing wrong before. By making the device optional, the forced downcast is conflicting with the output in an unnecessary manner. I was reading the error as it being about the incoming type being already matched, not the outgoing one. That makes sense now, and should be fine.

I was just paranoid about pulling in anything that could break one of my builds, given how fragile they are at the moment.

**Pull request merged**
