### PR TITLE
[MovieInput]fix MovieInput decode issue

### PR DESCRIPTION
**Pull request by lyb0307**
Using "CVOpenGLESTextureCacheCreateTextureFromImage" function to
generating "luminanceTexture" and "chrominanceTexture". This could
avoid some byte-aligning issue
#182

### CODE REVIEW

**Comment by omarojo** [comment]
would this help with supporting Video Recording with audio when using MovieInput.?
ie. Audio from the movie file source.

**Comment by joshbernfeld** [comment]
This fixes distortion issues with videos where the width is not a multiple of 16 e.g. 1080x1920. 
Thank you very much!!

For example:

image-1 1

**Comment by joshbernfeld** [comment]
Caution this does fix distortion issues but inserts two frame buffers into the cache for every frame processed. This results in a runaway cache and runaway CPU usage. You need to remove these two lines.

`luminanceFramebuffer.cache = sharedImageProcessingContext.framebufferCache`

`chrominanceFramebuffer.cache = sharedImageProcessingContext.framebufferCache`

**Comment by joshbernfeld** [comment]
The MovieInput for Mac is nearly identical to the one for iOS. I would recommend you take a look at the changes that were made in this commit and implement them in the MovieInput file for Mac to see if that fixes it.

**Comment by kirillbagrinovsky** [comment]
Thank you for response 
I see there is no fix for Mac OS version, but I port it it by myself (like in iOS implementation)
Can somebody help in fixing of this problem in GPUImage version 1?
I tried to port this commit, but it did not end well(((
This bug is very important for me, because there is no way to process screen recordings of different sizes

**Comment by joshbernfeld** [comment]
@kirillbagrinovsky @BradLarson I wanted to come back and shed some light on why this fixed the distortion issue with videos where the width is not a multiple of 16. 

The problem was that the pixel buffer line stride was not the same as the pixel buffer width. The line stride is the total length in bytes of a row in the pixel buffer including padding. Whereas the pixel buffer width is the number of actual pixels without any padding.

Most pixels buffers we were dealing with did not have any padding since their pixel widths were a multiple of 16 and easily fit into memory. This is why the issue only appeared infrequently e.g. with a video size of 1080x1920.

When we had a video with the dimensions 1080x1920 and called glTexImage2D to move the pixels from the pixel buffer into the texture we were under the impression that the size of the pixel buffer was the value returned by CVPixelBufferGetWidth: 1080. But if we called CVPixelBufferGetBytesPerRow(pixelBuffer)/4 it would return 1088, this would imply there was 8 pixels of padding. I believe that when glTexImage2D would iterate through the pixels in the pixel buffer it was including the padding as pixels. More frustratingly, the developer documentation for [CVPixelBufferGetWidth](https://developer.apple.com/documentation/corevideo/1457241-cvpixelbuffergetwidth?language=objc) does not mention that it doesn't include padding: "The width of the buffer, in pixels."

The issue was resolved by this commit because glTexImage2D was removed and instead texture caches were used that altogether alleviated the need to manually transfer the pixel data.

**Comment by BradLarson** [comment]
@joshbernfeld - Thanks for the detailed commentary. This is an issue that recurred in several places, and I recall seeing the same thing you did. Unfortunately, I lost track of things when I didn't have the time to work on this in the last couple of years, and the new job has complicated my contributions to these projects.

I'm getting some of that straightened out now, and Janie is taking over the maintenance of many of these projects, so I'll fill her in on this.

**Comment by joshbernfeld** [comment]
@BradLarson I totally understand - no worries at all. Thank you!!

**Pull request merged**
