### PR TITLE
Added Hough Transform Line Detection.  OSX only for now.

### LINKED ISSUE #50: Hough Transform for Line Detection
It was in the first GPUImage but hasn't been ported over yet.  This would also require the Parallel Coordinates transform be ported over.

### PR DESCRIPTION
**Pull request by maxcan**
Mostly a direct port from GPUImage 1.  OSX Only.  Will come later.

partially closes #50

### CODE REVIEW

**Comment by wantondevious** [comment]
Hi, I couldn't pull this branch under Xcode 8, Swift 3. Lots of errors :/

**Comment by maxcan** [comment]
Yes. It was pushed out before swift 3 but not merged. Haven't gotten around
to updating it yet.

**Comment by wantondevious** [comment]
I'd offer to help but I have 2 days experience with Swift :)

W

**Comment by maxcan** [comment]
I probably wont get to get to this this week, but will try to soon.

**Comment by maxcan** [comment]
closing in favor of #94

**Comment by wantondevious** [comment]
Thanks Brad!!

W

**Pull request closed without merging**
