### PR TITLE
Fix: Front Camera Issue in iOS

### PR DESCRIPTION
**Pull request by ShivaHuang**
Original patch from https://github.com/BradLarson/GPUImage2/pull/70.
With an additional fix for mirrored output of front camera.

### CODE REVIEW

**Comment by ShivaHuang** [comment]
Updated for Xcode 8.3

**Comment by ShivaHuang** [comment]
@BradLarson Can you help review this patch and merge it?

**Comment by chengkaizone** [comment]
It's very good!

**Comment by mahdidham** [comment]
why didn't replace `.landscapeLeft` to `landscapeRight` for  frontface @ShivaHuang @BradLarson?

**Comment by alexpell00** [comment]
Works great!

**Pull request merged**
